IF OBJECT_ID('[dbo].[USP_ssf_Account]') IS NOT NULL
	DROP PROCEDURE [dbo].[USP_ssf_Account];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[USP_ssf_Account] AS
BEGIN
SELECT [﻿ID]
     , ISDELETED
     , MASTERRECORDID
     , NAME
     , TYPE
     , RECORDTYPEID
     , PARENTID
     , BILLINGSTREET
     , BILLINGCITY
     , BILLINGSTATE
     , BILLINGPOSTALCODE
     , BILLINGCOUNTRY
     , BILLINGSTATECODE
     , BILLINGCOUNTRYCODE
     , BILLINGLATITUDE
     , BILLINGLONGITUDE
     , BILLINGGEOCODEACCURACY
     , BILLINGADDRESS
     , PHONE
     , FAX
     , ACCOUNTNUMBER
     , WEBSITE
     , PHOTOURL
     , INDUSTRY
     , USAGE_ALERT_EMAIL_DISTRIBUTION__C
     , ACCESS_LEVEL__C
     , ACCOUNT_OWNER_FULL_NAME__C
     , BILLING_CONTACT__C
     , MCS_ID__C
     , DUPLICATE_GROUP__C
     , DUPLICATE_SCORE__C
     , POTENTIAL_DUPLICATE__C
     , RECORD_CHECKED__C
     , ACCEL_EXTERNAL_ID__C
     , ORACLE_EXTERNAL_ID__C
     , EXTERNAL_ID__C
     , DATA_QUALITY_DESCRIPTION__C
     , DATA_QUALITY_SCORE__C
     , DUPCHECK__DC3DISABLEDUPLICATECHECK__C
     , DUPCHECK__DC3INDEX__C
     , ZUORA__CUSTOMERPRIORITY__C
     , ZUORA__NUMBEROFLOCATIONS__C
     , ZUORA__SLAEXPIRATIONDATE__C
     , ZUORA__SLASERIALNUMBER__C
     , ZUORA__SLA__C
     , ZUORA__UPSELLOPPORTUNITY__C
     , OLD_BILLING_STATE__C
     , OLD_BILLING_COUNTRY__C
     , BILLING_COUNTRY_NAME
     , BILLING_COUNTRY_CODE
     , BILLING_STATE_NAME
     , BILLING_STATE_CODE
     , RED_Gate_ID FROM dbo.Account_FF
END

GO
